name: Build YTBlock

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Copiar main.js
        run: cp electron/main.js main.js
      - name: Build Windows
        run: npx electron-builder --win --publish never
        env:
          GH_TOKEN: ""
      - uses: actions/upload-artifact@v4
        with:
          name: YTBlock-Windows
          path: dist/*.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Copiar main.js
        run: cp electron/main.js main.js
      - name: Build Mac
        run: npx electron-builder --mac --publish never
        env:
          GH_TOKEN: ""
      - uses: actions/upload-artifact@v4
        with:
          name: YTBlock-Mac
          path: dist/*.dmg
